### ISSUE TITLE
get_avatar格式错了

### ISSUE THREAD

**Issue by Zxilly** [hjthjthjt/rnmaterial#10]
`get_avatar(1,44,'avatar');`才是正确写法。。。
您写的是`get_avatar(1,44,avatar);`
alt属性不是这么设的...
这么写会报一个`Warning: Use of undefined constant avatar - assumed 'avatar' (this will throw an Error in a future version of PHP) in \wp-content\themes\rnmaterial\single.php on line 17`

**Comment by TigerBeanst** [comment]
从来没报错过……

**Comment by Zxilly** [comment]
@hjthjthjt 因为这是一个warning,一般来说production的网站都会忽视warning级别的错误，你可以看看自己的头像上有没有avatar这个alt
