### ISSUE TITLE
要求更换主题中 daily_pic 模块和 sidebar 的图片

### ISSUE THREAD

**Issue by neoFelhz** [hjthjthjt/rnmaterial#2]
两张图片 tower 和 cloud 是我的个人摄影作品，本人保留所有权利。

**Comment by TigerBeanst** [comment]
我这边的搜索结果：
daily_pic是来自Guuh Anjos的作品，而sidebar来自HTC One M8的一款公共壁纸，真的是你个人的摄影作品吗？
目前我会替换daily_pic以避免侵犯Guuh Anjos的版权，但sidebar暂不做变动。

**Comment by neoFelhz** [comment]
Guuh Anjos 的原作如下，为一加2的公开壁纸：
http://ww3.sinaimg.cn/bmiddle/870a5f40jw1euqxunxn5bj20u01hcdtw.jpg

**Comment by TigerBeanst** [comment]
此处在第六张：[http://imgur.com/gallery/tDQvf](http://imgur.com/gallery/tDQvf)
