### ISSUE TITLE
一个微小的请求

### ISSUE THREAD

**Issue by ChristianSwift** [hjthjthjt/rnmaterial#5]
大佬能做全站pjax吗？音乐播放器果然还是要pjax才能不间断播放呢

**Comment by TigerBeanst** [comment]
因为感觉网站基本整个主体都会因为访问页面而改变……
行吧我下次试试加进去¯\_(ツ)_/¯
不过我是咸鱼不知道能不能成功23333

**Comment by ghost** [comment]
我和viosey都期待着你的进一步改进，最好能够完全移植到wp来
加油喔！

**Comment by TigerBeanst** [comment]
@zzwl2016 最近比较忙，我自己博客也基本没管，不过我会尝试着更新的（代码水平弱的一比的我

**Comment by idawnlight** [comment]
然后真的诈尸级更新了 233

**Comment by TigerBeanst** [comment]
@LiMingYuGuang 大致问题解决了 233，现在应该主要剩下侧边栏的问题了
