### ISSUE TITLE
喷子一个

### ISSUE THREAD

**Issue by Rain-dew** [hjthjthjt/rnmaterial#6]
是不是总喜欢喷来喷去？你人生就这些意义吗？你以为自己站在多雄伟的道德高度？真看不起你这样的人

**Comment by idawnlight** [comment]
一脸懵逼，发生了什么

**Comment by ChristianSwift** [comment]
莫名其妙，看来看去就只有你在喷，还带电子邮件提醒的，真看不起你这样的人

**Comment by TigerBeanst** [comment]
@ChristianSwift  
@LiMingYuGuang  

你们大概看一下这个就知道这个人在想什么了
https://github.com/ibireme/YYKit/issues/393

**Comment by Rain-dew** [comment]
三个一起来我也不怕。人以群分！

**Comment by idawnlight** [comment]
我没有看出 @hjthjthjt 究竟有什么地方在喷，你觉得有问题自己改改提个 PR 啊，为什么要让作者改？作者没这个义务吧。
而且你去别人的项目开 issue 喷别人就是一种低素质行为，issue 不是用来撕逼的。

**Comment by Rain-dew** [comment]
你说这话没想到你朋友吧，就允许你朋友去撕逼？

**Comment by LarrySue** [comment]
有技术问题就说技术问题 觉得有BUG就自己改了提交 自己的BUG自己解决不了跑来喷人还当伸手党的就赶紧滚吧 工资这么好挣啊? 培训班没教过你水平不高就要夹着尾巴做人吗?

**Comment by idawnlight** [comment]
@Rain-dew 我没看出 @hjthjthjt 哪里有撕逼了，引用你的话
> 这是一个自由言论的地方，但是 1. 我正常问问题 2. 我没有在问题里骂人，说不好听的话 3. 我并不觉得我这样问有什么不好

1. 这是一个正常的反问句
2. 没有骂人，说不好听的话
3. 并不觉得这样有什么不好

反倒是你在别人的项目中开 issue 喷别人

哦对了我不认识 @hjthjthjt ，我只是 watch 了这个项目

**Comment by Rain-dew** [comment]
我问为什么不更新，没有强调一定要人家更新吧？这有什么不能说的？这就像我问你吃午饭了吗？你可以回答我，太忙顾不上。那么OK。。。我仅仅是问问而已，然而你的朋友呢，这么无聊，不喷一句过不下去。还有你们俩，一起来帮喷，那又怎样。我不会因为你们这样的行为晚上少吃一口饭！

**Comment by LarrySue** [comment]
那你记得多吃点啊

**Comment by Rain-dew** [comment]
我来这里就是不爽你朋友这种行为！真的看不下去，这么无聊的人。我也无妨效仿一下

**Comment by LarrySue** [comment]
我朋友是谁啊?

**Comment by ChristianSwift** [comment]
这就是你来乱喷然后推送给我们watch这个项目人的原因？
