### ISSUE TITLE
一点小问题，请教一下

### ISSUE THREAD

**Issue by purple11261126** [hjthjthjt/rnmaterial#7]
麻烦问一下，这个主题和 WP Editor.md（markdown） 插件有冲突，导致代码高亮显示不正确，我希望能够用那个插件编辑文章，应该在哪里注释掉主题的 pre code 样式，感谢大侠指点一下~~

**Comment by TigerBeanst** [comment]
@purple11261126 啊那个插件我也在用_(:з」∠)_
高亮的问题我会处理的，介意等我考完试修吗23333
前面在纠结那个弱智的为什么代码块不换行的问题，昨晚修了，这个高亮本来就要弄¯\_(ツ)_/¯

**Comment by purple11261126** [comment]
感谢大侠，完全不介意，对，我这也是发现代码块不换行，今天问了那个插件的作者，他说是主题干扰，那就等待大侠考完试修改啦。感谢，感谢~~
另外，如果能简单注释掉哪里就可以让插件接管编辑器的话，方便告诉我一下么~~

**Comment by TigerBeanst** [comment]
@purple11261126 那个应该是本身存在于css/style.min.css里的样式，但是这个主题绝大多数样式是直接从原主题拉过来的我也没怎么看23333
你对着那个CSS文件删一下相关内容？
（代码块的部分今天凌晨一两点的时候已经push了¯\_(ツ)_/¯）

**Comment by purple11261126** [comment]
OK，感谢，预祝考试好成绩~~

**Comment by TigerBeanst** [comment]
应该修好了，你测试看看（请务必要看README.md）

**Comment by purple11261126** [comment]
我来下载测试一下，非常感谢。
美好的寒假在向你招手~~

**Comment by TigerBeanst** [comment]
@purple11261126 
![](https://i.loli.net/2018/01/17/5a5f516c0cdf9.jpg)
预告一下……

**Comment by purple11261126** [comment]
期待首映~~

**Comment by purple11261126** [comment]
今天发现更新，甚是欢喜，立刻更新~~
友情提示一下，发现一处笔误：head.php 当中，第 9、10 两行都是调用了 seo_author
再次感谢更新~~超喜欢这个主题

**Comment by TigerBeanst** [comment]
@purple11261126 啊吼的，找时间改
