### ISSUE TITLE
评论邮件提醒不能用

### ISSUE THREAD

**Issue by Zxilly** [hjthjthjt/rnmaterial#8]
我知道这1000%是我自己的问题，而且我也排除了一些故障(比如和WP Mail SMTP不兼容)
然后这个应该怎么调试啊，怎么判断一个action是否执行了呢，关于这个能不能给一点建议，谢谢。

**Comment by TigerBeanst** [comment]
印象中有个SMTP发信的插件（挺好找的）是自带一部分测试邮件的发送日志的，你也可以找一下
（毕竟我也不会修hhhh）

**Comment by Zxilly** [comment]
修好了，WP Editor.MD修改了评论的钩子，所以挂掉了
